[package]
name = "rtic-serial-interrupt"
version = "0.1.0"
authors = ["René Rössler <rene@freshx.de>"]
edition = "2018"
publish = false

[dependencies]
cortex-m-rtic = { version = "0.5.9", default-features = false, features = [
    "cortex-m-7",
] }
panic-semihosting = "0.5.3"
cortex-m-semihosting = "0.3.5"

[dependencies.nrf51-hal]
path = "../../nrf51-hal"
optional = true

[dependencies.nrf52810-hal]
path = "../../nrf52810-hal"
optional = true

[dependencies.nrf52811-hal]
path = "../../nrf52811-hal"
optional = true

[dependencies.nrf52832-hal]
path = "../../nrf52832-hal"
optional = true

[dependencies.nrf52833-hal]
path = "../../nrf52833-hal"
optional = true

[dependencies.nrf52840-hal]
path = "../../nrf52840-hal"
optional = true

[features]
51 = ["nrf51-hal"]
52810 = ["nrf52810-hal"]
52811 = ["nrf52811-hal"]
52832 = ["nrf52832-hal"]
52833 = ["nrf52833-hal"]
52840 = ["nrf52840-hal"]
